version: '3.3'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - minio_vds
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - dev

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
      - SPRING_DATASOURCE_USERNAME=${DB_USER}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - dev

  frontend:
    build:
      context: ./frontend
    networks:
      - dev

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "PGPASSWORD=postgres pg_isready --username=postgres --dbname=communify"]
      interval: 1s
      timeout: 1s
      retries: 10
    networks:
      - dev

  minio_vds:
    image: minio/minio
    container_name: minio_vds
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_PROMETHEUS_AUTH_TYPE: "public"
      TARGET_BUCKET_NAME: communify-images
    command: server /data --address ":9000" --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev

  setup-minio:
    image: minio/mc
    depends_on:
      - minio_vds
    environment:
      MC_HOST_minio: http://minioadmin:minioadmin@minio_vds:9000
      TARGET_BUCKET_NAME: communify-images
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for MinIO...';
      sleep 5;
      echo 'Checking/creation of bucket communify-images...';
      mc mb minio/communify-images --ignore-existing;
      echo 'Setting policy download...';
      mc anonymous set download minio/communify-images;
      echo 'MinIO configuration completed.';
      "
    networks:
      - dev

networks:
  dev:

volumes:
  postgres_data:
  minio_data: