spring:
    application:
        name: communify
    
    datasource:
        url: jdbc:postgresql://localhost:5432/communify
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
    
    jpa:
        hibernate:
            ddl-auto: update
        # show-sql: true
    cache:
        type: redis
        redis:
            time-to-live: 1h
            key-prefix: recommendations
            cache-null-values: false
    data:
        redis:
            host: localhost
            port: 6379

server:
    servlet:
        context-path: /api

logging:
    level:
        org:
            springframework:
                security: DEBUG

jwt:
    secret: jhw48giusljkfsnq03u9gbyr655uatyiuejilrkf1nbjsfdyautugy1ihu
    expiration: 30000000

minio:
    url: http://127.0.0.1:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: communify-images